# MAIN base
baseURL = "https://languagechatbot.ru/"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = false
theme = "apsho"
enableRobotsTXT = true
publishDir = "docs"

# Languages
[languages]
  [languages.ru]
    languageName = "Русский"
    languageCode = "ru-ru"
    weight = 1
    contentDir = "content/ru"
    title = "Language Chatbot AI"

  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2
    contentDir = "content/en"
    title = "Language Chatbot AI"

# Navigation Bar (Russian)
[[languages.ru.menu.main]]
name = "Главная"
url = "#hero"
weight = 1
[[languages.ru.menu.main]]
name = "Возможности"
url = "#feature"
weight = 2
[[languages.ru.menu.main]]
name = "FAQ"
url = "#faq"
weight = 3

# Navigation Bar (English)
[[languages.en.menu.main]]
name = "Home"
url = "#hero"
weight = 1
[[languages.en.menu.main]]
name = "Features"
url = "#feature"
weight = 2
[[languages.en.menu.main]]
name = "FAQ"
url = "#faq"
weight = 3

# Footer Sitemap (Russian)
[[languages.ru.menu.sitemap]]
name = "Главная"
url = "#hero"
weight = 1
[[languages.ru.menu.sitemap]]
name = "Возможности"
url = "#feature"
weight = 2
[[languages.ru.menu.sitemap]]
name = "FAQ"
url = "#faq"
weight = 3

# Footer Sitemap (English)
[[languages.en.menu.sitemap]]
name = "Home"
url = "#hero"
weight = 1
[[languages.en.menu.sitemap]]
name = "Features"
url = "#feature"
weight = 2
[[languages.en.menu.sitemap]]
name = "FAQ"
url = "#faq"
weight = 3

# Footer Address
[params.address]
address = ""
email = "support@languagechatbot.ru"
phone = ""

# Footer Social (оставь пустым или заполни своими ссылками)
[params.social]
facebook = ""
twitter = ""
github = ""

[params]
# Header
logo = "images/logo.png"

# Contact form (если не используешь - оставь пустым)
fabFormURL = ""

# Analytics (если не используешь - оставь пустым)
googleAnalytics = ""

# App links
[params.app]
name = "Language Chatbot AI"
package = "com.buddy.chat"
rustoreURL = "https://www.rustore.ru/catalog/app/com.buddy.chat"

# Footer
footerTitle = "Получайте новости и обновления приложения"
copyright1 = "Все права защищены"
copyright2 = "Copyright © {year} <a href=\"https://languagechatbot.ru/\" target=\"_blank\">languagechatbot.ru</a>"

# contact
email = "support@languagechatbot.ru"

